/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface;

import Business.DB4Outil.DB4OUtil;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.Employee.Employee;
import Business.Role.CitizenRole;
import Business.Role.Role;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author mahes
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    private EcoSystem system;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    private boolean logoutToClose=false, citizen=false;

    public MainJFrame() {
        initComponents();
        system = dB4OUtil.retrieveSystem();
        
        btnLogout.setEnabled(false); 
        btnLogout.setVisible(false);
        
        jLabel3.setVisible(false);
    }
    
    public void logInBtnPress(){
        btnLogout.setVisible(true);
        btnLogout.setEnabled(true);
        
        btnLogin.setEnabled(false);
        btnLogin.setVisible(false);
        
        btnNewCitizen.setEnabled(false);
        btnNewCitizen.setVisible(false);
        
        txtUserName.setEnabled(false);
        txtUserName.setVisible(false);      
        
        txtPassword.setEnabled(false);
        txtPassword.setVisible(false);
       
            jLabel1.setVisible(false);
            jLabel2.setVisible(false);
            jLabel3.setVisible(true);

            lblLocation.setVisible(true);
            lblMainPanelName.setVisible(true);
        
       
        
    }
    
    public void logOutBtnPress(){
        btnLogout.setVisible(false);
        btnLogout.setEnabled(false);
        
        btnLogin.setEnabled(true);
        btnLogin.setVisible(true);
        
        btnNewCitizen.setEnabled(true);
        btnNewCitizen.setVisible(true);
        
        txtUserName.setEnabled(true);
        txtUserName.setVisible(true); 
        txtUserName.setText("");
        
        txtPassword.setEnabled(true);
        txtPassword.setVisible(true);
        txtPassword.setText("");
        
        jLabel1.setVisible(true);
        jLabel2.setVisible(true);
        jLabel3.setVisible(false); 
        
        lblLocation.setVisible(false);
        lblLocation.setText("");
        
        lblMainPanelName.setVisible(false);
        lblMainPanelName.setText("");
    }
    
    public void fillLogInDetails(Organization inOrganization, Enterprise inEnterprise, Network inNetwork,UserAccount userAccount){
        if(inOrganization!=null){
            lblLocation.setText(inOrganization.getName() +"," +" "  +inEnterprise.getName() +" " +"Enterprise" +"," +" " +inNetwork.getName());
        }else if(inEnterprise!=null){
            lblLocation.setText(inEnterprise.getName() +" " +"Enterprise" +"," +" " +inNetwork.getName());
        }else{
            lblLocation.setText("System Admin");
        }
        
        lblMainPanelName.setText(userAccount.getEmployee().getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        mainJPanelTop = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        txtUserName = new javax.swing.JTextField();
        btnNewCitizen = new javax.swing.JButton();
        lblLocation = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblMainPanelName = new javax.swing.JLabel();
        userProcessContainer = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        mainJPanelTop.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setText("UserName:");

        jLabel2.setText("Password:");

        btnLogin.setText("LOGIN");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        btnLogout.setText("LOGOUT");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        txtUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserNameActionPerformed(evt);
            }
        });

        btnNewCitizen.setText("New Customer");
        btnNewCitizen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewCitizenActionPerformed(evt);
            }
        });

        lblLocation.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblLocation.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel3.setText("Logged in as:");

        lblMainPanelName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        javax.swing.GroupLayout mainJPanelTopLayout = new javax.swing.GroupLayout(mainJPanelTop);
        mainJPanelTop.setLayout(mainJPanelTopLayout);
        mainJPanelTopLayout.setHorizontalGroup(
            mainJPanelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainJPanelTopLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnLogout)
                .addGap(27, 27, 27)
                .addGroup(mainJPanelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainJPanelTopLayout.createSequentialGroup()
                        .addComponent(btnLogin)
                        .addGap(47, 47, 47)
                        .addComponent(btnNewCitizen)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(132, 132, 132))
                    .addGroup(mainJPanelTopLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)))
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMainPanelName, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        mainJPanelTopLayout.setVerticalGroup(
            mainJPanelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainJPanelTopLayout.createSequentialGroup()
                .addGroup(mainJPanelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainJPanelTopLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainJPanelTopLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(mainJPanelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainJPanelTopLayout.createSequentialGroup()
                                .addGroup(mainJPanelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)
                                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(mainJPanelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnNewCitizen)
                                    .addComponent(lblLocation, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainJPanelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(lblMainPanelName, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jSplitPane1.setTopComponent(mainJPanelTop);

        userProcessContainer.setLayout(new java.awt.CardLayout());

        jLabel4.setFont(new java.awt.Font("Apple Chancery", 1, 48)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userInterface/usericon.png"))); // NOI18N
        jLabel4.setText("LIFE IMPROVIZATION SYSTEM");
        userProcessContainer.add(jLabel4, "card2");

        jSplitPane1.setRightComponent(userProcessContainer);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserNameActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
       
       if(logoutToClose){
           btnLogout.setText("LOGOUT");
       }
       
        logOutBtnPress();
        
        userProcessContainer.removeAll();
        JPanel blankJP = new JPanel();
        userProcessContainer.add("blank", blankJP);
        CardLayout crdLyt = (CardLayout) userProcessContainer.getLayout();
        crdLyt.next(userProcessContainer);
        dB4OUtil.storeSystem(system);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // Get user name
        String userName = txtUserName.getText();
        // Get Password
        char[] passwordCharArray = txtPassword.getPassword();
        String password = String.valueOf(passwordCharArray);

        //Step1: Check in the system user account directory if you have the user
        UserAccount userAccount = system.getUserAccountDirectory().authenticateUser(userName, password);
        
        Enterprise inEnterprise = null;
        Organization inOrganization = null;
        Network inNetwork = null;
        Role role=null; 
        
        if (userAccount == null) {
            //Step2: Go inside each network to check each enterprise
            for (Network network : system.getNetworkList()) {
                //Step 2-a: Check against each enterprise
                for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                    userAccount = enterprise.getUserAccountDirectory().authenticateUser(userName, password);
                    
                    if (userAccount == null) {
                        //Step3: Check against each organization inside that enterprise
                        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                            userAccount = organization.getUserAccountDirectory().authenticateUser(userName, password);
                            if (userAccount != null) {
                                inEnterprise = enterprise;
                                inOrganization = organization;
                                inNetwork = network;
                                role=userAccount.getRole();
                                break;
                            }
                        }
                    } else {
                        inEnterprise = enterprise;
                        inNetwork = network;
                        role=userAccount.getRole();
                        break;
                    }
                    if (inOrganization != null) {
                        break;
                    }
                }
                if (inEnterprise != null) {
                    break;
                }
            }
        }
        
        
        
        if (userAccount == null || userAccount.getUsername().equals("")) {
            JOptionPane.showMessageDialog(null, "Invalid Credentails!");
            return;
        } else if(role instanceof CitizenRole){
            citizen=true;
            //logOutBtnPress();
            CitizenJPanel cp = new CitizenJPanel(userProcessContainer, userAccount, inOrganization, inEnterprise,system,inNetwork);
            userProcessContainer.add("citizenRegistrationJPanel", cp);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer); 
            
            
        }else{           
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            userProcessContainer.add("workArea", userAccount.getRole().createWorkArea(userProcessContainer, userAccount, 
                    inOrganization, inEnterprise, system,inNetwork));
            layout.next(userProcessContainer);            
        }

        //lblMainPanelName.setText(userAccount.getEmployee().getName());
        
        fillLogInDetails(inOrganization, inEnterprise, inNetwork, userAccount);
        
        logInBtnPress();     
        if(citizen){
            jLabel3.setVisible(false);

            lblLocation.setVisible(false);
            lblLocation.setText("");

            lblMainPanelName.setVisible(false);
            lblMainPanelName.setText("");
        }     
          
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnNewCitizenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewCitizenActionPerformed
        // TODO add your handling code here:
        logoutToClose=true;
        
        logInBtnPress();
        btnLogout.setText("CLOSE");     
        jLabel3.setVisible(false);
        //
        CitizenRegistrationJPanel crj = new CitizenRegistrationJPanel(userProcessContainer,system);
        userProcessContainer.add("citizenRegistrationJPanel", crj);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnNewCitizenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnNewCitizen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel lblLocation;
    private javax.swing.JLabel lblMainPanelName;
    private javax.swing.JPanel mainJPanelTop;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUserName;
    private javax.swing.JPanel userProcessContainer;
    // End of variables declaration//GEN-END:variables


}
