/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.HealthVolunteerRole;

import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.HealthVolunteerOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkRequest.VolunteerToDoctor;
import Business.WorkRequest.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import userInterface.CitizenRole.ReportACrimeJPanel;

/**
 *
 * @author mahes
 */
public class HealthVolunteerWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userprocesscontainer;
    private UserAccount useraccount;
    private HealthVolunteerOrganization healthvolunteerorganization;
    private Network network;
    private Enterprise enterprise;

    /**
     * Creates new form HealthVolunteerWorkAreaJPanel
     */
    public HealthVolunteerWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, HealthVolunteerOrganization healthVolunteerOrganization, Network network, Enterprise enterprise) {

        initComponents();
        this.enterprise = enterprise;
        this.userprocesscontainer = userProcessContainer;
        this.useraccount = account;
        this.healthvolunteerorganization = healthVolunteerOrganization;
        this.network = network;
        populateHistorytable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRegister = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVolunteerWorkrequests = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRegister.setText("REQUEST FUNDS FOR A NEW PATIENT");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });
        add(btnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 360, 460, 30));

        tblVolunteerWorkrequests.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Patient ID", "Patient Name", "Disease", "Request Status"
            }
        ));
        jScrollPane1.setViewportView(tblVolunteerWorkrequests);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 920, 160));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel1.setText("REQUESTS HISTORY");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel3.setText("WORK AREA OF VOLUNTEER");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed

        regPatientandRequestDoctorJPanel registerPatientJPanel = new regPatientandRequestDoctorJPanel(userprocesscontainer, useraccount, healthvolunteerorganization, network, enterprise);
        userprocesscontainer.add("RegisterPatient", registerPatientJPanel);
        CardLayout layout = (CardLayout) userprocesscontainer.getLayout();
        layout.next(userprocesscontainer);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegisterActionPerformed

    public void populateHistorytable() {
        DefaultTableModel dtm = (DefaultTableModel) tblVolunteerWorkrequests.getModel();
        dtm.setRowCount(0);
        for (WorkRequest workRequest : useraccount.getWorkQueue().getWorkRequestList()) {
            Object[] row = new Object[6];
            row[0] = ((VolunteerToDoctor) workRequest).getPatientID();
            row[1] = ((VolunteerToDoctor) workRequest);
            row[2] = ((VolunteerToDoctor) workRequest).getDisease();
            //row[3] = workRequest.getReceiver();
        
            row[3] = workRequest.getStatus();
            dtm.addRow(row);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegister;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblVolunteerWorkrequests;
    // End of variables declaration//GEN-END:variables
}
