/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.SchoolRole;

import Business.Enterprise.Enterprise;
import Business.Network.Area;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author mahes
 */
public class PrincipalCampJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PrincipalCampJPanel
     */
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private Organization organization;
    private Network network;
    private Enterprise enterprise;
    private Area area;
    private int num[]={1,2,3,4,5,6,7,8,9,10};

    PrincipalCampJPanel(JPanel userProcessContainer, UserAccount userAccount, Organization organization, 
            Enterprise enterprise, Network network) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.organization = organization;
        this.network = network;
        this.enterprise = enterprise;

        
        btnRemove.setVisible(false);
        btnSubmit.setEnabled(false);
        populateArea();
        populateNumber();
    }
    
     public void populateArea() {
        comboArea.removeAllItems();

        for (Area a : network.getAreaList()) {
            comboArea.addItem(a);
        }
    }
     
     private void populateNumber(){
         comboNumber.removeAllItems();;
         
         for(int i: num){
             comboNumber.addItem(String.valueOf(i));
         }
     }
     
     private boolean validation(){
         return true;
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        comboArea = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        comboNumber = new javax.swing.JComboBox<>();
        btnBack = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();
        lblMsg = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Organize Camps");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(468, 84, -1, -1));

        comboArea.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboAreaActionPerformed(evt);
            }
        });
        add(comboArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 190, 172, -1));

        jLabel2.setText("jLabel2");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1017, 213, -1, 0));

        jLabel3.setText("Select Area:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 190, -1, -1));

        jLabel4.setText("Number of Students:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 250, -1, -1));

        comboNumber.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(comboNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 250, 172, -1));

        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 380, -1, -1));

        btnRemove.setText("Remove Camp");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });
        add(btnRemove, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 320, -1, -1));

        lblMsg.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblMsg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(lblMsg, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 130, 390, 20));

        btnSubmit.setText("Create Camp");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 320, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        // TODO add your handling code here:
        
       /* if (!validation()) {
            JOptionPane.showMessageDialog(null, "All are mandatory fields, enter appropriate data");
            return;
        }
        
        area.setCamp(false);
        area.setNumberPerCamp(0);
        
        populateArea();
        JOptionPane.showMessageDialog(null, "Success! Camp removed in" +" " +area);*/
               
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void comboAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboAreaActionPerformed
        // TODO add your handling code here:
        area=(Area) comboArea.getSelectedItem();
        if(area==null){
            return;
        }
        if(!area.isCamp()){
            lblMsg.setText("");            
            
            comboNumber.setEnabled(true);
            //btnRemove.setEnabled(false);
            btnSubmit.setEnabled(true);           
        }else{//if camp is already there
            lblMsg.setText("Camp already open in this area!");
            
            comboNumber.setEnabled(false);
           // btnRemove.setEnabled(true);
            btnSubmit.setEnabled(false);
        }
        
        
    }//GEN-LAST:event_comboAreaActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        
        if (!validation()) {
            JOptionPane.showMessageDialog(null, "All are mandatory fields, enter appropriate data");
            return;
        }
        
         int s=(Integer.parseInt((String) comboNumber.getSelectedItem())) ;
        
        area.setCamp(true);
        area.setNumberPerCamp(s);
        
        populateArea();
        JOptionPane.showMessageDialog(null, "Success! Camp now available for Students in" +" " +area);
    }//GEN-LAST:event_btnSubmitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JComboBox comboArea;
    private javax.swing.JComboBox<String> comboNumber;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblMsg;
    // End of variables declaration//GEN-END:variables
}
