/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.SchoolRole;

import Business.Enterprise.Enterprise;
import Business.Network.Area;
import Business.Network.Network;
import Business.Organization.CSROrganization;
import Business.Organization.CitizenOrganization;
import Business.Organization.Organization;
import Business.Role.ClassVacancy;
import Business.Role.Role;
import Business.Role.SchoolRole;
import Business.UserAccount.UserAccount;
import Business.WorkRequest.EducationFunds;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mahes
 */
public class RequestFundsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form RequestFundsJPanel
     */
    
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private Organization organization;
    private Network network;
    private Enterprise enterprise;
    private Role role;
    
    public RequestFundsJPanel(JPanel userProcessContainer, UserAccount userAccount, Organization organization, Enterprise enterprise, Network network) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.organization = organization;
        this.network = network;
        this.enterprise = enterprise;
        this.role=userAccount.getRole();
        
        populateTable();
    }
    
    private void populateTable(){
        DefaultTableModel model = (DefaultTableModel) tbl.getModel();

        model.setRowCount(0);

        for ( ClassVacancy cv:((SchoolRole)role).getClassVacancies() ) {


            Object[] row = new Object[3];

            row[0] = cv.getClassNumber();
            row[1] = cv.getVacancies();
            row[2] = cv.getTutionFee();
            
            model.addRow(row);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        lblCollected = new javax.swing.JLabel();
        btnFunds = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblNew = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Funding Details");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(474, 101, -1, -1));

        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Class", "Total Vacancies", "Tution/Vacancy($)"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbl);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 179, -1, 198));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setText("Previous Total Fund Required($):");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 250, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel4.setText("Total Fund Collected($):");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 290, -1, -1));

        lblTotal.setText("<>");
        add(lblTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 250, 97, 16));

        lblCollected.setText("<>");
        add(lblCollected, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 290, 97, 16));

        btnFunds.setText("Raise Funding");
        btnFunds.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFundsActionPerformed(evt);
            }
        });
        add(btnFunds, new org.netbeans.lib.awtextra.AbsoluteConstraints(457, 471, 144, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setText("Raise New Fund/Add to required funds>>");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 475, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel5.setText("New Funding Required($):");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 210, -1, -1));

        lblNew.setText("<>");
        add(lblNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 210, 97, 16));
    }// </editor-fold>//GEN-END:initComponents

    private void btnFundsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFundsActionPerformed
        // TODO add your handling code here:
        Role role=null;
        int funds= ((SchoolRole)role).calculateFunds();
        
        EducationFunds request = new EducationFunds();
        
        request.setReqFunds(String.valueOf(funds));
        
        //Organization org1=null
       // Organization org2=null        
        boolean success=true;
        for (Organization org : enterprise.getOrganizationDirectory().getOrganizationList()) {
            if (org instanceof CSROrganization) {
                success = true;
                
                org.getWorkQueue().getWorkRequestList().add(request);
                
            }
            
            if (org instanceof CitizenOrganization) {
                success = true;
                org.getWorkQueue().getWorkRequestList().add(request);
                
            }
        }
        
        userAccount.getWorkQueue().getWorkRequestList().add(request);

        if (success) {
            JOptionPane.showMessageDialog(null, "Success! Funding raised!");
        } else {
            JOptionPane.showMessageDialog(null, "Oops! Something went wrong");
        }
    }//GEN-LAST:event_btnFundsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFunds;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCollected;
    private javax.swing.JLabel lblNew;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTable tbl;
    // End of variables declaration//GEN-END:variables
}
