/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.SchoolRole;

import Business.Enterprise.Enterprise;
import Business.Network.Area;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.Organization.SchoolOrganization;
import Business.Role.Role;
import Business.Role.SchoolRole;
import Business.UserAccount.UserAccount;
import Business.WorkRequest.EduVolToSchoolWorkRequest;
import Business.WorkRequest.WorkRequest;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author mahes
 */
public class SchoolStudentUnregWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SchoolStudentWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private Organization organization;
    private Network network;
    private Enterprise enterprise;
    private ArrayList<Area> areaList;

    public SchoolStudentUnregWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, 
            Organization organization, Network network, Enterprise enterprise) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.organization = organization;
        this.network = network;
        this.enterprise=enterprise;
        this.areaList=network.getAreaList();
        lblNetwork.setText(network.getName());
        
        populateTable();
        
    }
    
    private void populateTable(){
        DefaultTableModel model = (DefaultTableModel) tblCamps.getModel();

        model.setRowCount(0);

        for (Area a:areaList ) {

            if ((!a.isCamp()) || (a.isCampFull())) {
                continue;
            }


            Object[] row = new Object[2];

            row[0] = a;
            row[1] = (a.getNumberPerCamp() - a.getNumberFilled());
            
            model.addRow(row);

        }
    }
    
    private void displayChart(){
        
        DefaultCategoryDataset dcd = new DefaultCategoryDataset();
        for (Area area : network.getAreaList()) {
            float percentage = 0; 
            int count = 0, literates = 0;

            for (WorkRequest wr : organization.getWorkQueue().getWorkRequestList()) {
                if (!(wr instanceof EduVolToSchoolWorkRequest)) {
                    continue;
                }

                Area a = ((EduVolToSchoolWorkRequest) wr).getArea();
                if (!a.equals(area)) {
                    continue;
                }

                if (((EduVolToSchoolWorkRequest) wr).isLiterate()) {
                    literates++;
                }
                count++;

            }

            percentage = (( literates* 100/count ) );
            dcd.addValue(percentage, "Literacy Rates", area.getName());
        }

        JFreeChart chart = ChartFactory.createBarChart("Bar Chart", "Area", "Literacy %", dcd);
        CategoryPlot plot = chart.getCategoryPlot();

        ChartFrame chrt = new ChartFrame("Literacy", chart);
        chrt.setVisible(true);
        chrt.setSize(500, 400);
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHeader = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblNetwork = new javax.swing.JLabel();
        btnLiteracy = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCamps = new javax.swing.JTable();
        lblStatus = new javax.swing.JLabel();
        btnRegistration = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblHeader.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeader.setText("STUDENT WORK AREA");
        add(lblHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(454, 96, 283, 29));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("You are currently not registered for Educational Camp Program in");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 167, -1, -1));

        lblNetwork.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNetwork.setText("<empty>");
        add(lblNetwork, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 167, 599, -1));

        btnLiteracy.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnLiteracy.setText("View Literacy Rates ");
        btnLiteracy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLiteracyActionPerformed(evt);
            }
        });
        add(btnLiteracy, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 225, 214, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setText("Camps Open To Join");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(511, 268, -1, -1));

        tblCamps.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "CAMPS", "Vacancies"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblCamps);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(452, 312, 256, 134));

        lblStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(lblStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(337, 475, 505, 23));

        btnRegistration.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnRegistration.setText("Register");
        btnRegistration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrationActionPerformed(evt);
            }
        });
        add(btnRegistration, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 510, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnLiteracyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLiteracyActionPerformed
        // TODO add your handling code here:
        displayChart();
    }//GEN-LAST:event_btnLiteracyActionPerformed

    private void btnRegistrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrationActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblCamps.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a valid row");
            return;
        }
        
        ((SchoolRole)userAccount.getRole()).setIsRegistered(true);
        Area ar = (Area) tblCamps.getValueAt(selectedRow, 0);
          for (Area a:areaList ) {
              if(ar.equals(a)){
                  a.incrementFilled();
                  ((SchoolRole)userAccount.getRole()).setArea(ar);
                  if( (a.getNumberPerCamp() - a.getNumberFilled() ) <= 0){
                      a.setCampFull(true);
                  }
              }
          }
          populateTable();
          JOptionPane.showMessageDialog(null, "Success, you are registered");
    }//GEN-LAST:event_btnRegistrationActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLiteracy;
    private javax.swing.JButton btnRegistration;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JLabel lblNetwork;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JTable tblCamps;
    // End of variables declaration//GEN-END:variables
}
