/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.DoctorRole;

import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.DoctorOrganization;
import Business.UserAccount.UserAccount;

import Business.WorkRequest.VolunteerToDoctor;
import Business.WorkRequest.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
//import userInterface.PoliceRole.ViewIncidentJpanel;

/**
 *
 * @author mahes
 */
public class DoctorWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DoctorWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private UserAccount useraccount;
    private DoctorOrganization doctororganization;
    private Network network;
    private Enterprise enterprise;

    public DoctorWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, DoctorOrganization doctorOrganization, Enterprise enterprise, Network network) {
        initComponents();
        this.doctororganization = doctorOrganization;
        this.userProcessContainer = userProcessContainer;
        this.useraccount = account;
        this.network = network;
        this.enterprise = enterprise;
        populateHistorytable();
        btnViewDetailsandProcess.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDoctorRequests = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        btnAssigntome = new javax.swing.JButton();
        btnViewDetailsandProcess = new javax.swing.JButton();
        btnRejectRequest = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 255));
        setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel1.setText("DOCTOR WORK AREA");

        tblDoctorRequests.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Patient ID", "Patient Name", "Contact", "Disease", "Duration", "Sender", "Status"
            }
        ));
        jScrollPane1.setViewportView(tblDoctorRequests);

        jLabel2.setText("DOCTOR WORK REQUEST HISTORY:");

        btnAssigntome.setText("Assign to Me");
        btnAssigntome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssigntomeActionPerformed(evt);
            }
        });

        btnViewDetailsandProcess.setText("View Details & Process");
        btnViewDetailsandProcess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDetailsandProcessActionPerformed(evt);
            }
        });

        btnRejectRequest.setText("Reject Request");
        btnRejectRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRejectRequestActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1))
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnViewDetailsandProcess)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAssigntome, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 586, Short.MAX_VALUE)
                        .addComponent(btnRejectRequest)))
                .addGap(70, 70, 70))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(342, 342, 342)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRejectRequest)
                        .addGap(33, 33, 33))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(btnAssigntome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)))
                .addComponent(btnViewDetailsandProcess)
                .addGap(0, 137, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAssigntomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssigntomeActionPerformed

        int selectedRow = tblDoctorRequests.getSelectedRow();

        if (selectedRow >= 0) {
            VolunteerToDoctor request = (VolunteerToDoctor) tblDoctorRequests.getValueAt(selectedRow, 1);

            if (request.getStatus()== "Patient sent to Doctor") {
                request.setStatus("Assigned to Doctor");
                request.setReceiver(useraccount);
                populateHistorytable();
                btnViewDetailsandProcess.setVisible(true);
            }
            else if(request.getStatus()== "Assigned to Doctor")
            {
             JOptionPane.showMessageDialog(this, "This request is already Assigned to You", "Sorry", JOptionPane.WARNING_MESSAGE);
             return;
            
            }
            
            else if (request.getStatus()== "CSR granted funds")
            {
                 JOptionPane.showMessageDialog(this, "This request has been Completed", "Sorry", JOptionPane.WARNING_MESSAGE);
            return;
            }
            
            else if (request.getStatus()== "Rejected by Doctor")
            {
                 JOptionPane.showMessageDialog(this, "This request has been Rejected already", "Sorry", JOptionPane.WARNING_MESSAGE);
            return;
            }
            
             
                //JOptionPane.showMessageDialog(this, "This request is in further process", "Sorry", JOptionPane.WARNING_MESSAGE);
            
        } else {
            JOptionPane.showMessageDialog(this, "PLEASE SELECT A ROW TO VIEW DETAILS", "NO INPUT DETECTED!!", JOptionPane.WARNING_MESSAGE);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnAssigntomeActionPerformed

    private void btnRejectRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRejectRequestActionPerformed

        int selectedRow = tblDoctorRequests.getSelectedRow();
        if (selectedRow >= 0) {
            VolunteerToDoctor request = (VolunteerToDoctor) tblDoctorRequests.getValueAt(selectedRow, 1);
            if (request.getStatus() == "Assigned to Doctor") {
                request.setStatus("Rejected by Doctor");
                populateHistorytable();
            } else {
                JOptionPane.showMessageDialog(this, "Cannot Reject this Request", "Sorry", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "PLEASE SELECT A ROW TO REJECT", "NO INPUT DETECTED!!", JOptionPane.WARNING_MESSAGE);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnRejectRequestActionPerformed

    private void btnViewDetailsandProcessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDetailsandProcessActionPerformed

        int selectedRow = tblDoctorRequests.getSelectedRow();

        if (selectedRow >= 0) {
            VolunteerToDoctor request = (VolunteerToDoctor) tblDoctorRequests.getValueAt(selectedRow, 1);
            if (request.getStatus() == "Assigned to Doctor") {
                ViewandProcessRequest panel = new ViewandProcessRequest(userProcessContainer, useraccount, enterprise, request);
                userProcessContainer.add("ViewandProcessRequest", panel);
                CardLayout layout = (CardLayout) userProcessContainer.getLayout();
                layout.next(userProcessContainer);
            }

            // TODO add your handling code here:
    }//GEN-LAST:event_btnViewDetailsandProcessActionPerformed
     else {
            JOptionPane.showMessageDialog(this, "PLEASE SELECT A ROW TO VIEW DETAILS", "NO INPUT DETECTED!!", JOptionPane.WARNING_MESSAGE);
        }
    }

    public void populateHistorytable() {
        DefaultTableModel dtm = (DefaultTableModel) tblDoctorRequests.getModel();
        dtm.setRowCount(0);
        for (WorkRequest workRequest : doctororganization.getWorkQueue().getWorkRequestList()) {
            Object[] row = new Object[7];
            row[0] = ((VolunteerToDoctor) workRequest).getPatientID();
            row[1] = ((VolunteerToDoctor) workRequest);
            row[2] = ((VolunteerToDoctor) workRequest).getContact();
            row[3] = ((VolunteerToDoctor) workRequest).getDisease();
            row[4] = ((VolunteerToDoctor) workRequest).getDuration();
            row[5] = workRequest.getSender();
            row[6] = workRequest.getStatus();
            dtm.addRow(row);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssigntome;
    private javax.swing.JButton btnRejectRequest;
    private javax.swing.JButton btnViewDetailsandProcess;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDoctorRequests;
    // End of variables declaration//GEN-END:variables
}
