/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.DoctorRole;

import Business.Enterprise.Enterprise;
import Business.Organization.CSROrganization;
import Business.Organization.CitizenOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkRequest.DoctorToCSRHead;
import Business.WorkRequest.DoctorToCitizenWorkreq;
import Business.WorkRequest.VolunteerToDoctor;
import com.sun.glass.events.KeyEvent;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import userInterface.DoctorRole.DoctorWorkAreaJPanel;

/**
 *
 * @author aravind
 */
public class ViewandProcessRequest extends javax.swing.JPanel {

    /**
     * Creates new form ViewandProcessRequest
     */
    private JPanel userProcessContainer;
    private UserAccount useraccount;
    private VolunteerToDoctor request;
    private Enterprise enterprise;

    public ViewandProcessRequest(JPanel userProcessContainer, UserAccount useraccount, Enterprise enterprise, VolunteerToDoctor request) {
        initComponents();

        this.request = request;
        this.userProcessContainer = userProcessContainer;
        this.useraccount = useraccount;
        this.enterprise = enterprise;
        lblDisease.setText(this.request.getDisease());
        lblPatientID.setText(String.valueOf(request.getPatientID()));
        lblPatientName.setText(this.request.getName());
        lblSender.setText(String.valueOf(this.request.getSender()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblPatientName = new javax.swing.JLabel();
        lblDisease = new javax.swing.JLabel();
        lblSender = new javax.swing.JLabel();
        lblPatientID = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtboxFunds = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtboxTreatment = new javax.swing.JTextField();
        btnRequestCSR = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Patient Name:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 175, 134, 32));

        jLabel2.setText("Health State:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 213, 128, 32));

        jLabel3.setText("Patient ID:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 137, 134, 32));

        jLabel4.setText("Sender:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 251, 131, 33));
        add(lblPatientName, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 175, 119, 32));
        add(lblDisease, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 213, 119, 32));
        add(lblSender, new org.netbeans.lib.awtextra.AbsoluteConstraints(547, 251, 119, 32));
        add(lblPatientID, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 137, 119, 32));

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel10.setText("CREATE A REQUEST FOR FUNDS");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 24, -1, -1));

        jLabel5.setText("Funds Needed (USD):");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(394, 329, 160, 33));

        txtboxFunds.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtboxFundsActionPerformed(evt);
            }
        });
        txtboxFunds.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtboxFundsKeyTyped(evt);
            }
        });
        add(txtboxFunds, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 330, 148, 33));

        jLabel6.setText("Diagnosis:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 290, 120, 33));

        txtboxTreatment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtboxTreatmentActionPerformed(evt);
            }
        });
        add(txtboxTreatment, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 290, 148, 33));

        btnRequestCSR.setText("Request for Funds");
        btnRequestCSR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestCSRActionPerformed(evt);
            }
        });
        add(btnRequestCSR, new org.netbeans.lib.awtextra.AbsoluteConstraints(565, 394, -1, -1));

        btnBack.setText("<< Previous Page");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 70, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    private void txtboxFundsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtboxFundsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtboxFundsActionPerformed

    private void txtboxTreatmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtboxTreatmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtboxTreatmentActionPerformed

    private void btnRequestCSRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestCSRActionPerformed

        if (!txtboxFunds.getText().isEmpty() || !txtboxTreatment.getText().isEmpty()) {
            
        String treatment = txtboxTreatment.getText();
        String funds = txtboxFunds.getText();
        boolean wrSuccess=false;
        
        request.setStatus("Request Sent for funds");

        DoctorToCSRHead request1 = new DoctorToCSRHead(treatment);

        request1.setPatientName(lblPatientName.getText());
        request1.setDisease(lblDisease.getText());
        request1.setTreatment(treatment);
        request1.setFunds(funds);
        request1.setSender(useraccount);
        request1.setStatus("Doctor request for funds");
        request1.setMessage(treatment);
        request1.setVolunteerToDoctorWorkRequest(request);

//        DoctorToCitizenWorkreq request2 = new DoctorToCitizenWorkreq(treatment);
//        request2.setPatientName("Aravind");
//        request2.setDisease(lblDisease.getText());
//        request2.setTreatment(treatment);
//        request2.setFunds(funds);
//        request2.setSender(useraccount);
//        request2.setStatus("Doctor request for funds");
//        request2.setMessage(treatment);
//        request2.setVolunteerToDoctorWorkRequest(request);

        Organization org = null;
        Organization orgCitizen = null;
        

        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
            if (organization instanceof CSROrganization ) {
                org = organization;
                break;
            }
        }
        
        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
            if (organization instanceof CitizenOrganization) {
                orgCitizen = organization;
                break;
            }
        }

        if (org != null) {

            org.getWorkQueue().getWorkRequestList().add(request1);
             wrSuccess=true;

        }
        
        if (orgCitizen != null) {

            orgCitizen.getWorkQueue().getWorkRequestList().add(request1);
             wrSuccess=true;

        }
        
        if(wrSuccess){
            useraccount.getWorkQueue().getWorkRequestList().add(request1);
        }

        JOptionPane.showMessageDialog(this, "Requested for funds", "Success", JOptionPane.INFORMATION_MESSAGE);
        }
        else{ 
        JOptionPane.showMessageDialog(this, "Cannot Serve a request without both the feilds", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRequestCSRActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed

        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        DoctorWorkAreaJPanel panel = (DoctorWorkAreaJPanel) component;
        panel.populateHistorytable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);

        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtboxFundsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtboxFundsKeyTyped


char ch = evt.getKeyChar();
    if(!(Character.isDigit(ch)||(ch == KeyEvent.VK_DELETE)|| ch== KeyEvent.VK_BACKSPACE))
    {
      evt.consume();
        JOptionPane.showMessageDialog(null,"Fund is an Integer");
        // TODO add your handling code here:
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtboxFundsKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRequestCSR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblDisease;
    private javax.swing.JLabel lblPatientID;
    private javax.swing.JLabel lblPatientName;
    private javax.swing.JLabel lblSender;
    private javax.swing.JTextField txtboxFunds;
    private javax.swing.JTextField txtboxTreatment;
    // End of variables declaration//GEN-END:variables
}
